### ISSUE TITLE
Variable not marked as unused if it is used in the other file.

### ISSUE THREAD

**Issue by YuraKotov** [Camelcade/Perl5-IDEA#1320]
Plugin version 2.119
Intellij idea on Win7

I have 2 files:
First have only definition.
Second definition and use this var.

Variable should be grey in the first file, but not.

**Comment by YuraKotov** [comment]
Global variable

**Comment by hurricup** [comment]
What find usages say on variable in question?

**Comment by YuraKotov** [comment]
Says - all usages from the other script.

**Comment by YuraKotov** [comment]
script1.pl:
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

our $our_var="";
$our_var = 1;
$our_var = 2;

script2.pl:
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

our $our_var="";

**Comment by YuraKotov** [comment]
![perl](https://cloud.githubusercontent.com/assets/152865/17513924/8b1ebf7c-5e38-11e6-9db9-e3b2f69ff3a2.png)

**Comment by hurricup** [comment]
From perl's perspective, these are same vars: `$main::our_var`
Atm plugin does not checking which files are really loaded in current script. So basically, for plugin, there is no difference between these variables. 
In real world - this is wrong, because there can be no relations between these two scripts, but this is intended behaviour. For now.
