### ISSUE TITLE
Unable to configure Perl5 SDK in Intellij on Mac OSX for plugin version 2016.3.1_7

### ISSUE THREAD

**Issue by bbmielke** [Camelcade/Perl5-IDEA#1404]
Unable to configure Perl5 SDK in Intellij on Mac OSX for plugin version 2016.3.1_7

Steps to produce the issue are:

1) Click on 'Perl5 SDK is not configured' --- 'Configure'
2) Select SDKs 
3) Hit the + sign
4) Select Perl5 Interpreter
5) Pick perl from OS --  /usr/local/perl/perls/perl-5.22.2/bin/perl
6) Nothing seemed to happen and I do not see the sdk added into the intellij window.
7) I also tested with something invalid and got a proper message indicating that there was a problem. (I pointed to /usr/local/perl).

Plugin Version: 2016.3.1_7
I also downloaded the .zip and tested this out with 2.200 from here directly and had the same problem.

Intellij: IC-163.7743.44
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-bit Server VM by JetBrains s.r.o

Perl installed from perlbrew at:

/usr/local/perl/perls/perl-5.22.2/bin/perl

(Also tested the problem with: /usr/local/perl/perls/perl-5.10.1/bin/perl)

My computer is running Mac OSX Sierra -- 10.12.1.

Unfortunately I do not have a mac at home, because I'd try to hop in and see if I can get more information/dig into the bug a bit more for you.

**Comment by hurricup** [comment]
According to our wiki, you should choose dir with perl, not perl executable. But this should be obvious for user, you are right.

**Comment by bbmielke** [comment]
Thanks for the comment.  I was able to correct my mistake.  I am wondering if you can add an error message for when someone points to the perl binary.  When I picked the wrong folder it gave a nice message, but when i pointed to the perl binary it was quiet.

**Comment by hurricup** [comment]
As I mentioned - you are not supposed to see perl executable at all. Probably it's an ide bug on macos. Will check.

**Comment by hurricup** [comment]
Checked with code, file chooser should suggest only directories, not files. Will check on mac ASAP

**Comment by thed0ctor** [comment]
Experienced this as well.

**Comment by bbmielke** [comment]
I have spent some time on my mac to look at this issue again.  When I cloned this repo and built the master the problem was gone.  I tested it in a clean setup with a checkout of tag 2.200release and the problem still exists.  I'd guess that any future release will clear the problem out.

**Comment by hurricup** [comment]
This is not a plugin bug. It is in IDEA or MAC ui/ui bingings. Still investigating. Have no mac, so moving slow

**Comment by bbmielke** [comment]
@hurricup as I said above the master branch on your repository works fine.  There's probably a library that you depend on that fixes the problem.  When you get close to cutting your next release, I'd be willing to run another test for you then, so that you can close this out, just let me know.

**Comment by hurricup** [comment]
Okay, thank you.

**Comment by Xdsxc** [comment]
Just a heads up, I just experienced this issue on IDEA 2017.1.1 build IC-171.4073.35, plugin version 2017.1.1

**Comment by hurricup** [comment]
Thank you. You may watch status of this bug here: https://youtrack.jetbrains.com/issue/IDEA-165899

**Comment by justin-robinson** [comment]
This bit me as well

**Comment by nyxee** [comment]
i have the problem too. IDEA 2017.1.2, perl plugin 2017.1.1.

After I select the directory as you suggest, the IDE continues to claim that the Perl5 SDK is not configured, but, i see the Perl syntax is clearly formatted.

**Comment by hurricup** [comment]
And your OS is?

**Comment by justin-robinson** [comment]
osx el capitan

**Comment by tasman-hayes** [comment]
Thanks for the plug-in. I hit this issue too. MacOS Sierra 10.12.5, phpStorm 2017.1.4.
Selecting the directory (/usr/bin) rather than the executable (/usr/bin/perl), as explained above, fixed the issue.
Note to see /usr/bin on Mac, I needed to use a key combination to go to this normally hidden path.
It would have been great if I could just have typed the path (I tried), or even better if it was just auto-detected.

**Comment by hurricup** [comment]
Hope to have a solution in the next major version.

**Comment by ikari7789** [comment]
Wow. Was super stuck until I found out here that you're supposed to select the parent folder rather than the perl folder itself. Just simply updating the text in the UI would help tremendously with this.

`Perl5 Interpreter:` is what is shown in the UI on Mac. This would be a lot more clear and precise if it said something like `Perl5 Executable Directory` or something. Also definitely as @tasman-hayes suggested. It shouldn't be all that difficult to automatically change it to the root directory if supplied an executable file.

@tasman-hayes On Mac, you can type a file path by `Cmd + Shift + G`, though your average user probably doesn't know this. Perhaps a note in the UI could also help there.

**Comment by hurricup** [comment]
@emrecio This is a different problem I believe. Please, start a separate issue.

**Comment by emrecio** [comment]
Got a new machine, and still the same problem with the latest version. Selecting the directory by pressing open (and not selecting a binary) worked. After I had to google it and found myself here again.
