### ISSUE TITLE
When debugging using "Perl remote debugging", the page displays "502 Bad Gateway"

### ISSUE THREAD

**Issue by juliazwang** [Camelcade/Perl5-IDEA#1664]
When debugging using "Perl remote debugging", if I don't click "Step Over" or other actions quickly enough, the page will display "502 Bad Gateway", if I keep clicking the actions, it will run successfully. Also, command output always displays "fatal: Not a git repository (or any of the parent directories): .git" when opening a page.

IDE name and version: IntelliJ IDEA 2017.2, build: #IU-172.4574.11
Perl5 plugin version: v2017.3.2
OS name and version: macOS High Sierra, Version 10.13.1
Browser: Safari, Version 11.0.1(13604.3.5)

screenshot 1 ("502 Bad Gateway"):
![screen shot 2017-12-12 at 5 05 24 pm](https://user-images.githubusercontent.com/23344955/33921497-ef4b24aa-df78-11e7-8f07-f1f52afb25d1.png)

screenshot 2 ("fatal: Not a git repository (or any of the parent directories): .git"):
![screen shot 2017-12-12 at 5 07 10 pm](https://user-images.githubusercontent.com/23344955/33921503-f7e7d950-df78-11e7-888c-79b131625cd7.png)

**Comment by hurricup** [comment]
Awesome! :)

This is a nginx error (possibly caused by a timeout) with some server error. Guess it's not related to debugger, but to your nginx configuration. 

fatal from starman/your script should be debugged and investigated. It's possible that cause is the debugger, but information you provided is not enough to make such assumption.
