### ISSUE TITLE
pmea files causes "multiple definition" warning

### ISSUE THREAD

**Issue by Zaitsev** [Camelcade/Perl5-IDEA#1792]
to allow plugin to parse pmea I have to add *.pmea to PerlModule File Type, so definitions in pmea causes "multiple definitions" warnings....

![image](https://user-images.githubusercontent.com/127843/45486430-b9b39700-b763-11e8-8bde-e985a6881c3a.png)

**Comment by hurricup** [comment]
Actually this has nothing to do with `pmea`. There is an inspection which controls duplicated namespaces. This inspection was necessary to me, but probably not so necessary for perl programmers, because it's a common practice to declare part of methods here and part - there. And in such cases you are writing `package Foo::Bar`. You can just turn off this inspection. 

Also I don't recommend to use an annotaions files you could see in the stale branch. Current plans are to make xml annotations files. Or yaml. Unsure yet. But that idea most likely won't make it to release.

**Comment by Zaitsev** [comment]
Thanks for advise. I have to use annotations due to some Moo::Role and Moo:Options methods not tracked by plugin. and they are excellent. 
as for yaml/XML for now when I set pmea as perl-file I have all syntax higlight and checks and perl-like look-n-feel. I'm pretty sure this will be impossible for yaml/XML
IMHO putting aside "multiple definitions" issue pmea is very good

**Comment by hurricup** [comment]
The problem is that if I want to make something not supported  by perl syntax, e.g. different signatures, extended docs, defaults, dunno what, It would be necessary to extend perl lexer and parser and this is pain. XML allows to specify anything I want in no time.
