### ISSUE TITLE
Libraries scripts are not working in system perl of Manjaro Linux. 

### ISSUE THREAD

**Issue by wjanes** [Camelcade/Perl5-IDEA#2141]
Hy

First of all thanks for your Plugin, well done :)
But i have a Problem installing modules via the quickfix or Popup.

e.g. if i want to start debugging it asks me to install Devel::Camelcadedb. But if i click on "install with cpan" or "Install Devel::Camelcadedb , an Error Popup raises saying "Missing Packages CPAN - Library is necessary to perform this action"

but i have cpan installed

IDE Version: Intellij IDEA Ultimate 2019.3
Perl5 Plugin Version: latest from marketplace (2019.3)
JRE Version: openjdk version 1.8.0.242
OS Name: Manjaro Linux

BR Wolfgang

**Comment by hurricup** [comment]
You've missed few details from issue template

**Comment by wjanes** [comment]
Sorry, i updated the missing information

**Comment by hurricup** [comment]
What is your perl, how installed, which version manager

**Comment by wjanes** [comment]
I have the perl version 5.30.1.
Installed via PACMAN package manager in Manjaro Linux

**Comment by hurricup** [comment]
Ok. I've not checked such scenario. Only Windows with strawberry perl/berrybrew and linux with apt-installed perl and/or plenv/perlbrew. 
I see 3 options here:
1. You try to install prelbrew and perl with it. And check how it goes.
2. You try to fetch plugin sources and debug what is going wrong (shouldn't be too hard).
3. Wait till I fix this (I've got a kid recently, so can't give you any ETA)

**Comment by wjanes** [comment]
No Problem i can wait :)

**Comment by hurricup** [comment]
Ok. I have no Manjaro Linux myself, so i'm checking with docker image.

1. I've got manjaro linux image and it has perl 5.30.1 installed. 
2. `perl` binary works fine. It's located in `/usr/bin/perl` and this path presents in `PATH` variable.
3. `cpan` command doesn't work because it's executable for some reason located in `/usr/bin/core_perl` and this path is not in `PATH` variable. 

Currently plugin looking for binary files in `perl`'s directory and binary directories of `@INC` roots.

I personally see set up like this for the first time and don't really know why it been done this way. 

If your configuration is the same, copying  scripts from `/usr/bin/core_perl` to the perl binary containing dir (`/usr/bin` in my case) should help. Still if you'll install other libraries with binaries and they will go to the `core_perl` dir, you'll need to make a copy again. Please check and let me know if it was the issue.

**Comment by wjanes** [comment]
hi @hurricup 
i will try it today and will let you know.

**Comment by wjanes** [comment]
@hurricup 

yes, now it would install but fails at the end because it would like to install in /usr/bin without root :)

**Comment by hurricup** [comment]
yes, this is expected. Manipulations with system perl should be done using `sudo` and plugin can't do that yet.
I strongly recommend to use a version manager, it makes life easier and safer. I prefer `perlbrew` myself.

**Comment by wjanes** [comment]
ok. thanks for your help, stay safe and healthy :)
