### ISSUE TITLE
Adding syntax support for Future::AsyncAwait and the Mojo::Base 'async_await' flag

### ISSUE THREAD

**Issue by stackqu** [Camelcade/Perl5-IDEA#2144]
Hi!
Please, add support for this syntax in Mojolicious plugin:
https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#async-await
Current plugin version (2020.1) reports an error on a construction like this: 

`use Mojo::Base -strict -async_await;`
`async sub foo {...}` 

Or this:

`use Future:AsyncAwait;`
`async sub foo {...}`

(plugin reports " semicolon expected " on strings with keyword 'async')

IDE version:
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 2010M
Cores: 4

**Comment by hurricup** [comment]
Ok. I've implemented basic support: parsing, highlighting, formatting, quick-doc and live templates.
Take a note, that code insight (type inferrence) is not working. Plugin will think that sub return plain value, instead of `Feature` wrapping plain value. I've create a separate issue #2145 for this, but this may not be so easy.

**Comment by akarelas** [comment]
I think this bug-fix is not complete. The async keyword only works like this:
```perl
async sub foo {
    # ...
}
```

But it does not work at all well with anonymous subs as expressions:
```perl
my $s = async sub {
    # ...
};
```

See attached image.
![async](https://user-images.githubusercontent.com/423822/104991782-39368c80-5a28-11eb-81a0-e65833c5f704.png)
