### ISSUE TITLE
Document why fancy method calls are "not recommended"

### ISSUE THREAD

**Issue by rillig** [Camelcade/Perl5-IDEA#2332]
GoLand 2020.3, Build #GO-203.5981.98, built on November 25, 2020
Perl5 plugin 203.5784.10-EAP-SNAPSHOT

The inspection 'Perl5 | Fancy method calls' says:

> Using of fancy calls is not recommended, use Pkgs->new()

The description of the inspection says:

> Checks for 'fancy' method calls, like new Foo::Bar();, which is not recommended.

This description raises the following questions:

* What exactly is a _fancy_ method call?
* Why is it _not recommended_?
* What's the proper replacement?

These questions should be answered in the description of the inspection.

**Comment by hurricup** [comment]
Fancy is `new Foo::Bar` instead of `Foo::Bar->new` (last one is canonical). It's not recommended by perldoc, see https://perldoc.perl.org/perlobj#Indirect-Object-Syntax
Quickfix suggests the proper replacement.
Feel free to submit a PR with better inspection description: https://github.com/Camelcade/Perl5-IDEA/blob/master/plugin/core/resources/inspectionDescriptions/FancyMethodCall.html
