### ISSUE TITLE
Space after semicolon (;)

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2523]
There's space after comma code style option, but not after semicolon.

It's odd when commas are spaced while semicolons (statement terminators) are not.

![image](https://user-images.githubusercontent.com/68062695/202184773-cfdbe135-c1dd-4a8f-bdbe-262ea4e49e77.png)

Can we add this option as well?

Should be easy to do so I think.

**Comment by hurricup** [comment]
This plugin is the kinda opposite to TIMTOWDY.
TIMTOWDY is good when you are playing alone on your own project. 
And for that you don't need IDE, editor would be enough. It is faster and lighter. 

This plugin was intended for the large complex projects with large teams. And in such projects things should be unified one way or another. IMHO there is no place for "I do because I can". 

And yes, you still can write whatever you want, but without built it formatter :D
