### ISSUE TITLE
Annotations for own pseudo keywords and operators

### ISSUE THREAD

**Issue by leobm** [Camelcade/Perl5-IDEA#2562]
Hi, 

I have another idea for a meaningful annotation. 

There are the following packages. Syntax::Operator or Syntax::Keyword.

But if I then use e.g. a new pseudo keyword/operator, it is not displayed in the IDE (in the syntaxhighlighter) like a normal keyword. 

Wouldn't it be cool if you could define the following annotations in your source code.

`#@keywords keyword1 keyword2....`

and 
`#@operators |> ==> 
`
or so....

**Comment by hurricup** [comment]
Feels like it would be better to add some project-level settings/config for this, not annotation. 

Also this looks theoretically interesting, but will complicate project and degrade overall performance because of these dynamic operators. 
Probably worth doing as a separate plugin for the perl plugin. But I personally won't do this. This plugin is intended to cover mainstream functionality you may need for enterprise development. It can't physically cover all things perl could do, because they are endless :D
