### ISSUE TITLE
Implement testing support

### ISSUE THREAD

**Issue by dimentox** [Camelcade/Perl5-IDEA#805]
Should go to test work? Would be nice to generate tests or run tests for a module.

**Comment by hurricup** [comment]
Not sure i understand what are you talking about. Please, be more specific. And specify your plugin version.

**Comment by hurricup** [comment]
Upd: seems you mean create test for class and so on. Atm tests are not supported (except t files support with few livetemplates) but in time, yes. Anyway, after debugger.

**Comment by mdklatt** [comment]
I think @dimentox is talking about the ability to create a Run/Debug configuration to run tests.

I don't know anything about the IDEA plugin architecture, but there must be a way to run an external process. For example, the [BashSupport](https://github.com/jansorg/BashSupport) plugin lets you create a Run configuration to execute a bash script. A Perl test configuration could run `prove` on the selected test directory, and then send the output to the IDEA test reporter. CLion's test runner displays TAP output from Google Test; maybe that functionality is available to IDEA plugins.

**Comment by hurricup** [comment]
Someone need to make https://github.com/maxmind/TAP-Formatter-TeamCity work.
I'm not ready for this right now.

**Comment by tomk3003** [comment]
Since this seems to take longer, could you provide a way to run `prove -m -v` from the run configuration?
This  would be very convenient.

**Comment by mdklatt** [comment]
@tomk3003 You can make a simple shell script to run `prove`, and use the [BashSupport plugin](https://www.plugin-dev.com/project/bashsupport/) to create a run configuration for it.

**Comment by hurricup** [comment]
You can probably just make a perl run configuration with `prove` as a perl script.

**Comment by tomk3003** [comment]
Ok, my description was a bit too short. What I want to do is, run the tests in the current `.t` script with Ctrl+Shift+F10 and being able to run this in the debugger if needed. For this to work I'll need to run `prove -m` instead of the perl interpreter. Running just the script works, but diag output is not where it should be. Setting `perl/bin/prove` as perl5 parameter works for run, but debugging will then debug the prove script itself instead of the test script. 
The nicest to have option would be, being able to run an arbitrary command as the current interpreter. That way I could run whatever I want.

**Comment by tomk3003** [comment]
Ahh! Found the problem. That is not an issue with perl/prove at all. It is a longstanding bug 
in IDEA [IDEA-70016](http://youtrack.jetbrains.com/issue/IDEA-70016). STDOUT and STDERR get mangled in run output. I'll just redirect STDERR to STDOUT and everything's fine. I'll just lose the color for STDERR.

**Comment by hurricup** [comment]
@tomk3003 see related issue about run configuration.
Also, i'll try to investigate possibility to merge outputs. See https://github.com/Camelcade/Perl5-IDEA/issues/1936
